### ISSUE TITLE
Implement system of flags

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#43]
Requested by Michael McCoy, he asks that we implement a set of flags (ex. "no show", "late checkin", "late checkout", etc) and that "close as inconclusive" (issue #42) be one of them. The main page should have the option to show only certain flags or to sort by flags.

**Comment by dwmorrin** [comment]
Who are the flags for?  Users or admin? 

For users we have implemented "no show" as an option when you click on the student name.  Is Michael McCoy aware of this feature?  (If so, does he want it changed?)  I would object to users manually flagging something as a "late" on 2 points:
1) The computer can calculate time.  The user does not need to redundantly do this.
2) Asking a user to click a "late" box is like asking them to click the "punishment" box.  Our users will not want to do this.  Let the computer be the bad guy.

For admin, the plan is to implement these as searchable items in the "closed forms" view.  Does the search feature not fulfill this role?

Regarding the "close as inconclusive" flag: I'm not sure what is typically "inconclusive" about a form and would love to hear examples.

**Comment by michaelphagen** [comment]
His example is that 5 xlr are checked out an only 4 are returned. I figured 
it was most logical to leave the form open but he wants to have the option 
to close the form even if not all items are returned (and the student needs 
to leave immediately). I still don't see why we couldn't leave the form 
open and I can bring this up with him again.
________________________________

Michael Hagen
Recorded Music Technician

Clive Davis Institute of Recorded Music
Tisch School of the Arts
New York University
194 Mercer St, #517
New York, NY 10012
914-299-3142

**Comment by dwmorrin** [comment]
Following the pattern established with clicking on a student name:

**Case:** item not able to be returned
**Handler:** click on item,  select a default option (e.g. "item lost") or open ended `textarea`.

This gives us a chance to update the inventory then and there.

**Comment by dwmorrin** [comment]
Todo:
* click on item opens modal with list of options such as "item cannot be returned" (like the student modal)
* fix click-on-student modal so that the "never showed up" and "left without signing out" options allow the form to be submitted

**Comment by michaelphagen** [comment]
I've made a lot of progress with this today, Tomorrow's goal is to make sure that the handler differentiate between clicking on the item description or ID and clicking on the quantity, as clicking on the quantity in my current sandbox shows a combination of both modal windows

**Comment by michaelphagen** [comment]
I've added the "item missing" and "student didn't sign out" cases to the change Log.
